
# htpasswd encoded credentials for access to the registry.
# Must be set on deployment.
auth:
  htpasswd: ~

registry:
  image: registry:2.7.1
  imagePullPolicy: IfNotPresent

nginx:
  image: nginx:1.19.3
  imagePullPolicy: IfNotPresent
