apiVersion: cert-manager.io/v1                                                                                         
kind: Certificate             
metadata:        
  name: epinio                  
  namespace: epinio    
spec:                                      
  dnsNames:  
  - epinio.{{ .Values.systemDomain }}
  issuerRef:                                              
    kind: ClusterIssuer  
    name: {{ .Values.server.tlsIssuer }}
  secretName: epinio-tls
