---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: staging-triggers-admin
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - clustertriggerbindings
  verbs:
  - get
  - list
  - watch
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: staging-triggers-admin
  namespace: tekton-staging
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - triggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: staging-triggers-admin
  namespace: tekton-staging
secrets:
  - name: registry-creds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: staging-triggers-admin-binding
  namespace: tekton-staging
subjects:
  - kind: ServiceAccount
    name: staging-triggers-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: staging-triggers-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: staging-triggers-admin-binding
subjects:
  - kind: ServiceAccount
    name: staging-triggers-admin
    namespace: tekton-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: staging-triggers-admin
---
# Make the service account admin for now, only
# because of the new stuff (like LRPs, images, etc.)
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: epinio-staging
subjects:
- kind: ServiceAccount
  name: staging-triggers-admin
  namespace: tekton-staging
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
