---
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-reporter
  namespace: eirini-core
data:
  task-reporter.yml: |
    enable_multi_namespace_support: true
    cc_tls_disabled: false
    completion_callback_retry_limit: 10
