---
apiVersion: v1
kind: ConfigMap
metadata:
  name: instance-index-env-injector
  namespace: eirini-core
data:
  instance-index-env-injector.yml: |
    enable_multi_namespace_support: false
    app_namespace: eirini-workloads
    service_name: instance-index-env-injector
    service_namespace: eirini-core
    service_port: 8443

