name: Build-images

on:
  push:
    branches: [ main ]
    paths:
    - 'images/linkerd-Dockerfile'
    - '.github/workflows/container-images.yml' # in case we change the versions below

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CFCIBOT_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CFCIBOT_DOCKERHUB_PASSWORD }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build linkerd
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: images/linkerd-Dockerfile
          tags: splatform/epinio-linkerd:2.11.1
          build-args: |
            LINKERD_VERSION=stable-2.11.1
            LINKERD_CHECKSUM=96c08570b6f6ad40ef1e6aa970959c9c5541e36c85477ee9843b85b8fdcc54ea
            KUBECTL_VERSION=v1.23.0
            KUBECTL_CHECKSUM=2d0f5ba6faa787878b642c151ccb2c3390ce4c1e6c8e2b59568b3869ba407c4f
