name: Build draft binaries - QA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  release:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      # A tag is mandatory but it will not be pushed in the repo
      # because we do not release
      - name: Create fake tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v99.0.0 -m "Fake tag for QA" --force

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Login to avoid quota
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JUADK_DOCKERHUB_USERNAME }}
          password: ${{ secrets.JUADK_DOCKERHUB_PASSWORD }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: 1.9.2
          args: release --skip-announce --skip-validate --skip-sign --config .goreleaser-qa.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
